theme: jekyll-theme-minimal
description: [I'm a STEM curriculum designer, LEGO designer, passoinate in AI, Deep learning and selfdrivig cars]
title: Mohamed Tarek Mohamed
logo: [11497486.jpeg]
show_downloads: ["true"]

