theme: jekyll-theme-minimal
description: I’m a computer engineer and educator, exploring how new technologies can help young people develop as creative thinkers. AI, Computer vision and robotics enthusiastic. 
title: Mohamed Tarek
logo: logo1.png
show_downloads: false

